### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by remoteVoyager** [remoteVoyager/GameOfLife#1]
- [x]  Build a data structure to store the board state

- [x]  “Pretty-print” the board to the terminal

- [x]  Given a starting board state, calculate the next one

- [x]  Run the game forever
